// Generated by js_of_ocaml 2.8+git-2646c43
/* 
ocamlfind ocamlc -linkpkg -o search.byte -package js_of_ocaml.syntax -syntax camlp4o -package js_of_ocaml search.ml&& js_of_ocaml search.byte
*/
(function(g){"use strict";var
$="Sys_error",ao=224,an="Invalid_argument",_="g",o=1024,am="jsError",Z=57343,al="search",ak=512,aj="End_of_file",ai="Failure",Y="Undefined_recursive_module",ah="Stack_overflow",f=128,d="",X=192,z=" : file already exists",U=56320,V=240,W=2048,a=248,ag="Not_found",S="Assert_failure",T="/",ad="packages",ae="Sys_blocked_io",af="fd ",R="Out_of_memory",ac="Match_failure",ab="Division_by_zero",aa=1e3;function
a$(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
bl(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
D(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=o,c-=o)f+=e.apply(null,bl(a,b,Math.min(c,o)));return f}function
aq(a){if(a.t==2)a.c+=a$(a.l-a.c.length,"\0");else
a.c=D(a.c,0,a.c.length);a.t=0}function
A(a){if((a.t&6)!=0)aq(a);return a.c}function
as(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
bg(a){for(var
l=d,e=d,i,h,j,b,c=0,k=a.length;c<k;c++){h=a.charCodeAt(c);if(h<f){for(var
g=c+1;g<k&&(h=a.charCodeAt(g))<f;g++);if(g-c>ak){e.substr(0,1);l+=e;e=d;l+=a.slice(c,g)}else
e+=a.slice(c,g);if(g==k)break;c=g}b=1;if(++c<k&&((j=a.charCodeAt(c))&-64)==f){i=j+(h<<6);if(h<ao){b=i-12416;if(b<f)b=1}else{b=2;if(++c<k&&((j=a.charCodeAt(c))&-64)==f){i=j+(i<<6);if(h<V){b=i-925824;if(b<W||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((j=a.charCodeAt(c))&-64)==f&&h<245){b=j-63447168+(i<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;e+="\ufffd"}else
if(b>65535)e+=String.fromCharCode(55232+(b>>10),U+(b&1023));else
e+=String.fromCharCode(b);if(e.length>o){e.substr(0,1);l+=e;e=d}}return l+e}function
bf(a){switch(a.t){case
9:return a.c;default:aq(a);case
0:if(as(a.c)){a.t=9;return a.c}a.t=8;case
8:return bg(a.c)}}function
i(a,b,c){this.t=a;this.c=b;this.l=c}i.prototype.toString=function(){return bf(this)};function
a8(a,b){throw[0,a,b]}function
c(a){return new
i(0,a,a.length)}function
aw(a,b){a8(a,c(b))}var
e=[0];function
ar(a){aw(e.Invalid_argument,a)}function
l(a){if(a<0)ar("String.create");return new
i(a?2:9,d,a)}function
a1(){var
b=g.console?g.console:{},c=["log","debug","info","warn","error","assert","dir","dirxml","trace","group","groupCollapsed","groupEnd","time","timeEnd"];function
d(){}for(var
a=0;a<c.length;a++)if(!b[c[a]])b[c[a]]=d;return b}function
bh(a){for(var
h=d,c=h,b,j,e=0,i=a.length;e<i;e++){b=a.charCodeAt(e);if(b<f){for(var
g=e+1;g<i&&(b=a.charCodeAt(g))<f;g++);if(g-e>ak){c.substr(0,1);h+=c;c=d;h+=a.slice(e,g)}else
c+=a.slice(e,g);if(g==i)break;e=g}if(b<W){c+=String.fromCharCode(X|b>>6);c+=String.fromCharCode(f|b&63)}else
if(b<55296||b>=Z)c+=String.fromCharCode(ao|b>>12,f|b>>6&63,f|b&63);else
if(b>=56319||e+1==i||(j=a.charCodeAt(e+1))<U||j>Z)c+="\xef\xbf\xbd";else{e++;b=(b<<10)+j-56613888;c+=String.fromCharCode(V|b>>18,f|b>>12&63,f|b>>6&63,f|b&63)}if(c.length>o){c.substr(0,1);h+=c;c=d}}return h+c}function
p(a){var
b=9;if(!as(a))b=8,a=bh(a);return new
i(b,a,a.length)}function
h(a){aw(e.Sys_error,a)}function
a2(a){if(!a.opened)h("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}var
ay=0;function
bm(){return new
Date().getTime()/aa}function
E(){return Math.floor(bm())}function
j(a){this.data=a;this.inode=ay++;var
b=E();this.atime=b;this.mtime=b;this.ctime=b}j.prototype={truncate:function(){this.data=l(0);this.modified()},modified:function(){var
a=E();this.atime=a;this.mtime=a}};function
v(a){return a.l}function
av(a){a=a
instanceof
i?a.toString():a;h(a+": No such file or directory")}var
aZ=T;function
t(a){a=a
instanceof
i?a.toString():a;if(a.charCodeAt(0)!=47)a=aZ+a;var
e=a.split(T),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
k(){this.content={};this.inode=ay++;var
a=E();this.atime=a;this.mtime=a;this.ctime=a}k.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
w=new
k();w.mk(d,new
k());function
C(a){var
b=w;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))av(a.orig);b=b.get(a[c])}return b}function
be(a){var
c=t(a),b=C(c);return b
instanceof
k?1:0}function
ba(a){return new
i(4,a,a.length)}function
B(a){if(g.Uint8Array)var
c=new(g.Uint8Array)(a.l);else
var
c=new
Array(a.l);var
e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
bn(a){if(a.t!=4)B(a);return a.c}function
a0(a,b){var
f=t(a),d=w;for(var
g=0;g<f.length-1;g++){var
e=f[g];if(!d.exists(e))d.mk(e,new
k());d=d.get(e);if(!(d
instanceof
k))h(f.orig+z)}var
e=f[f.length-1];if(d.exists(e))h(f.orig+z);if(b
instanceof
k)d.mk(e,b);else
if(b
instanceof
j)d.mk(e,b);else
if(b
instanceof
i)d.mk(e,new
j(b));else
if(b
instanceof
Array)d.mk(e,new
j(ba(b)));else
if(b.toString){var
l=c(b.toString());d.mk(e,new
j(l))}else
ar("caml_fs_register");return 0}function
bd(a){var
b=w,d=t(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
q(a,b,c){if(e.fds===undefined)e.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?v(b.data):0;d.flags=c;e.fds[a]=d;e.fd_last_idx=a;return a}function
bo(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
g=a.toString(),j=t(a);if(d.rdonly&&d.wronly)h(g+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)h(g+" : flags Open_text and Open_binary are not compatible");if(bd(a)){if(be(a))h(g+" : is a directory");if(d.create&&d.excl)h(g+z);var
i=e.fd_last_idx?e.fd_last_idx:0,f=C(j);if(d.truncate)f.truncate();return q(i+1,f,d)}else
if(d.create){var
i=e.fd_last_idx?e.fd_last_idx:0;a0(a,l(0));var
f=C(j);return q(i+1,f,d)}else
av(a)}q(0,new
j(l(0)));q(1,new
j(l(0)));q(2,new
j(l(0)));function
a3(a){var
b=e.fds[a];if(b.flags.wronly)h(af+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true,refill:null}}function
ap(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?D(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?D(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)B(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
bj(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
bk(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}var
u=new
Array();function
a_(a,b){var
h=c(b),d=v(h),g=v(a.file.data),f=a.offset;if(f+d>=g){var
e=l(f+d);ap(a.file.data,0,e,0,g);ap(h,0,e,f,d);a.file.data=e}a.offset+=d;a.file.modified();return 0}function
at(a){var
b;switch(a){case
1:b=bk;break;case
2:b=bj;break;default:b=a_}var
f=e.fds[a];if(f.flags.rdonly)h(af+a+" is readonly");var
c={file:f.file,offset:f.offset,fd:a,opened:true,buffer:d,output:b};u[c.fd]=c;return c}function
a4(){var
a=0;for(var
b
in
u)if(u[b].opened)a=[0,u[b],a];return a}function
a6(a){return a
instanceof
Array?a[0]:a
instanceof
i?252:aa}function
b(a,b,c){e[a+1]=b;if(c)e[c]=b}var
au={};function
a9(a,b){au[A(a)]=b;return 0}var
a7=0;function
n(a){a[2]=a7++;return a}function
bb(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
bc(a,b,c){c&=255;if(a.t!=4){if(b==a.c.length){a.c+=String.fromCharCode(c);if(b+1==a.l)a.t=0;return 0}B(a)}a.c[b]=c;return 0}function
ax(a){return a}function
a5(a){return au[a]}function
bi(a){if(a
instanceof
Array)return a;if(g.RangeError&&a
instanceof
g.RangeError&&a.message&&a.message.match(/maximum call stack/i))return ax(e.Stack_overflow);if(g.InternalError&&a
instanceof
g.InternalError&&a.message&&a.message.match(/too much recursion/i))return ax(e.Stack_overflow);if(a
instanceof
g.Error)return[0,a5(am),a];return[0,e.Failure,p(String(a))]}var
x=[a,c(ag),-7],F=[a,c(S),-11];b(11,[a,c(Y),-12],Y);b(10,F,S);b(9,[a,c(ae),-10],ae);b(8,[a,c(ah),-9],ah);b(7,[a,c(ac),-8],ac);b(6,x,ag);b(5,[a,c(ab),-6],ab);b(4,[a,c(aj),-5],aj);b(3,[a,c(an),-4],an);b(2,[a,c(ai),-3],ai);b(1,[a,c($),-2],$);b(0,[a,c(R),-1],R);n([a,c("Pervasives.Exit"),0]);a3(0);at(1);at(2);n([a,c("Array.Bottom"),0]);var
aA=c("Sys.Break"),aB=c("CamlinternalFormat.Type_mismatch"),aG=c("Js.Error"),aK=c("table"),aJ=c("input"),aI=c("Dom_html.Canvas_not_available"),aN=c("[\\][()\\\\|+*.?{}^$]"),aS=c("tbl"),aT=c("name"),aO=[0,c("search.ml"),9,45],aU=c(ad),aV=c(ad),aX=c(al),aY=c(al);function
G(a){var
e=v(a);if(0===e)return a;var
h=l(e),i=e-1|0,k=0;if(!(i<0)){var
c=k;for(;;){var
b=bb(a,c),n=65<=b?90<b?0:1:0;if(n)var
d=0;else{if(X<=b)if(214<b)var
f=1;else
var
d=0,f=0;else
var
f=1;if(f){if(216<=b)if(222<b)var
g=1;else
var
d=0,g=0;else
var
g=1;if(g)var
j=b,d=1}}if(!d)var
j=b+32|0;bc(h,c,j);var
m=c+1|0;if(i!==c){var
c=m;continue}break}}return h}n([a,aA,0]);n([a,aB,0]);var
H=[0,0];function
I(a){H[1]=[0,a,H[1]];return 0}var
r=g,m=null,aD=undefined;function
J(a){return a==m?0:[0,a]}var
K=r.RegExp,aF=r.Array,L=n([a,aG,0]),y=[0,L,{}],aE=false,aC=a6(y)===a?y:y[1];a9(c(am),aC);(function(a){throw a});I(function(a){return a[1]===L?[0,p(a[2].toString())]:0});I(function(a){return a
instanceof
aF?0:[0,p(a.toString())]});var
aH=r.document;n([a,aI,0]);r.HTMLElement===aD;function
M(a,b){var
c=a.toString();return b.tagName.toLowerCase()===c?b:m}var
aL=a1(0);function
N(a){return new
K(A(a),_)}function
aM(a,b,c){a.lastIndex=c;var
d=a.exec(A(b)),e=d==m?m:[0,d.index,d];return J(e)}new
K("[$]",_);N(aN);function
O(a){var
b=aH.getElementById(a.toString());if(b==m){aL.log(a.toString());throw[0,F,aO]}return b}function
s(a,b){var
c=J(a);if(c)return c[1];throw x}function
aP(a){return a.style.display="none"}function
aQ(a){return a.style.display=d}function
aR(a,b){var
e=b.rows.length,f=1;if(!(e<1)){var
c=f;for(;;){try{var
d=s(b.rows.item(c),aS),h=G(p(s(d.cells.item(0),aT).innerHTML));if(0===aM(N(G(p(a))),h,0))aP(d);else
aQ(d)}catch(f){f=bi(f);if(f!==x)throw f}var
g=c+1|0;if(e!==c){var
c=g;continue}break}}return 0}var
aW=s(M(aK,O(aU)),aV),P=s(M(aJ,O(aX)),aY);function
Q(a){aR(P.value,aW);return aE}P.onkeyup=function(a){if(1-(a==m?1:0)){var
c=Q(a);if(!(c|0))a.preventDefault();return c}var
d=event,b=Q(d);if(!(b|0))d.returnValue=b;return b};function
az(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{a2(d)}catch(f){}var
b=c;continue}return 0}}az(a4(0));return}(function(){return this}()));
